### ISSUE TITLE
Can you append pictures to your readme?)

### ISSUE THREAD

**Issue by andermirik** [you741/FEHeroes_Sim#1]
I wonder how it liiks but i don't want to build it

**Comment by immycat** [comment]
Lol it's been so long since I worked on this I don't think I even have the original files. I kind of given up on this. I'll try to find the images for you though.

**Comment by immycat** [comment]
Update: The only image I found is of the menu which is just a list of ugly buttons. Sorry man.
But it was pretty incomplete, all I had was a build a character thing which was just dropdown menus selecting skills and buttons. Then I had a map builder where you can just drag some tiles and units onto the map. That was it.

**Comment by andermirik** [comment]
Thx for answer)🙂
